{% set name = "featuretools_sql" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/featuretools_sql-{{ version }}.tar.gz
  sha256: 354e91dda4c34d852f31c312f57143538f8e5285d230af616fff390926a9d02f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }},<4.0
    - numpy >=1.17.5
    - pandas >=1.3.0
    - featuretools >=1.5.0
    - psycopg2 >=2.9.3
    - sqlalchemy >=1.4.2
    - PyMySQL >=1.0.2
    - snowflake-sqlalchemy >=1.4.2

test:
  imports:
    - featuretools_sql
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  doc_url: https://featuretools.alteryx.com/en/stable/guides/sql_database_integration.html
  dev_url: https://github.com/alteryx/featuretools-sql
  home: https://pypi.org/project/featuretools-sql/
  summary: directly import your relational data into Featuretools to run automated feature engineering
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stefaniesmith
    - sbadithe
    - ozzieD
    - machineAYX
    - rwedge
    - tamargrey
    - thehomebrewnerd
    - gsheni
    - dvreed77
